int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int root_finder(int root, int n);
int is_prime_number(int n);
int prime_checker(int divider, int n);
int is_palindrome(char *s);
int polyndrome_checker(char *s, int i, int n);
int wildcmp(char *s1, char *s2);
